name: OliverBradley
favicon: null
layout_spectrum: 0
typography_spectrum: 0.25355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111c20'
    - '#283940'
    - '#bdcfdc'
    - '#858c91'
    - '#576d79'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.16001995163969696
  rhythmicContrast: 0.21170819993130863
purpose: []
